### ISSUE TITLE
Not usable in 1.0

### ISSUE THREAD

**Issue by dzannotti** [dzannotti/vscode-babel#1]
Investigate the cause of the breakage (theme seems to break too)

**Comment by dzannotti** [comment]
After 1.0 release investigation it looks like default languages are not overwritable anymore. Not sure if wanted behaviour or regression https://github.com/Microsoft/vscode/issues/5278#issuecomment-210188595

**Comment by jakeargent** [comment]
@dzannotti The issue I had had been there ever since I updated VS Code some months ago. Back when I first installed VSC (around September 2015, give or take a month) auto-indentation and code completion worked by default. It stopped working after updating, but at the time I was busy writing code for a final exam and didn't submit a bug report. The point is, issue with python usability is not new to 1.0 version. Addition of the extensions didn't do anything at all. For python VSC is basically a bare bones text-field.
