### ISSUE TITLE
Some React issues

### ISSUE THREAD

**Issue by markgoodyear** [dzannotti/vscode-babel#2]
Firstly, this has made VS Code useable now, thanks! I just have one small issue left that may not be for the responsibility of this plugin, but reporting just incase you're able to look into it. In React / React Native, the highlighting breaks when using JSX inside an element/component prop:

```jsx
<Component prop={ /* Code here doesn't get highlighted */ } />
```

Here is a screenshot with Sublime Text on the left and VS Code on the right, using the Material theme on both to demonstrate what I mean:

![img](http://d.pr/i/fhmw/4wp2EV8A+)

Thanks!

**Comment by dzannotti** [comment]
Hi @markgoodyear,
Thanks for your feedback and for reporting the issue! I'm not a material theme user but by checking what's happening here,
In a nutshell the way this extension works is by parsing the code and emitting tags for each section, each tag is then colored by theme accordingly (you can inspect those via F1 -> Developer tool -> click on the prop), In your case console is marked (correctly) as class `token body braces class console curly embedded expression group js meta object round source support tag type jsx`, the .log part as `token body braces class console curly embedded expression function group js meta round source support tag jsx` and the string as `token body braces class curly embedded expression group js meta quoted round single source string tag jsx`. I strongly suspect that Material Theme does not color those types for some reason and this ticket should belong in there rather than here.
As suggested in the readme.md the only theme that currently will support most coloring tags should be [Spacemacs theme](https://github.com/dzannotti/vscode-theme-spacemacs). However i did not finish (or started for a fact) JSX coloring yet as i am currently traveling (eta end of next week).
Feel free to reopen the issue if you feel it's the case

**Comment by markgoodyear** [comment]
Hey @dzannotti, I did try the Spacemacs theme, but it has the same output. I get the same with the dev tools so just looks down to the theme needing to implement the highlighting. Thanks for taking a look! :+1:
